services:
  balances:
    build: ./balances
    volumes:
      - ./balances:/balances
    ports:
      - "3000:3000"
  hub:
    build: ./hub
    command: bash -c "npm run start:dev"
    volumes:
      - ./hub:/exchange/hub
    ports:
      - "3001:3000"
  tx_pool:
    build: ./tx_pool
    volumes:
      - ./tx_pool:/exchange/tx_pool
    ports:
      - "3002:3000"